/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metricssuite;

import java.text.DecimalFormat;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

//Cleanup Done
public class FunctionPointsPane extends javax.swing.JPanel {

    /**
     * Creates new form FunctionPointsPane
     */
    private String nameOfPane = "";
    private int externalInput = 0;
    private int externalOutput = 0;
    private int externalInquiries = 0;
    private int internalLogicalFiles = 0;
    private int externalInterfaceFiles = 0;
    private int weightingFactorEI = 4;
    private int weightingFactorEO = 5;
    private int weightingFactorEInq = 4;
    private int weightingFactorILF = 10;
    private int weightingFactorEIF = 7;
    private int externalInputResults =0;
    private int externalOutputResults = 0;
    private int externalInquiriesResults = 0;
    private int internalLogicalFilesResults = 0;
    private int externalInterfaceFilesResults = 0;
    private int totalCount = 0;
    private double computeFP = 0.0;
    private int valueAdjustmentSum = 0;
    private double codeSize =0;
    private String language = "";
    private int [] valueAdjustmentList = {0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    private String [] complexities = {"average", "average", "average", "average", "average"};
    private DecimalFormat df = new DecimalFormat("###,###,###.##");
    private MainFrame mainframe;
    
    public FunctionPointsPane() {
        initComponents();
    }
    
    public FunctionPointsPane(String nameOfPane, String language, MainFrame mainframe) {
        initComponents();
        this.nameOfPane = nameOfPane;
        this.language = language;
        this.mainframe = mainframe;
        languageData.setText(language);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EIsButtonGroup = new javax.swing.ButtonGroup();
        EOsButtonGroup = new javax.swing.ButtonGroup();
        EInqsButtonGroup = new javax.swing.ButtonGroup();
        ILFsButtonGroup = new javax.swing.ButtonGroup();
        EIFsButtonGroup = new javax.swing.ButtonGroup();
        computeFPButton = new javax.swing.JButton();
        valueAdjustmentButton = new javax.swing.JButton();
        computeCodeSizeButton = new javax.swing.JButton();
        changeLanguageButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EIsEdit = new javax.swing.JTextField();
        EOsEdit = new javax.swing.JTextField();
        EInqsEdit = new javax.swing.JTextField();
        ILFsEdit = new javax.swing.JTextField();
        EIFsEdit = new javax.swing.JTextField();
        EISimpleRadioButton = new javax.swing.JRadioButton();
        EIAverageRadioButton = new javax.swing.JRadioButton();
        EIComplexRadioButton = new javax.swing.JRadioButton();
        EOSimpleRadioButton = new javax.swing.JRadioButton();
        EOAverageRadioButton = new javax.swing.JRadioButton();
        EOComplexRadioButton = new javax.swing.JRadioButton();
        EInqSimpleRadioButton = new javax.swing.JRadioButton();
        EInqAverageRadioButton = new javax.swing.JRadioButton();
        EInqComplexRadioButton = new javax.swing.JRadioButton();
        ILFSimpleRadioButton = new javax.swing.JRadioButton();
        ILFAverageRadioButton = new javax.swing.JRadioButton();
        ILFComplexRadioButton = new javax.swing.JRadioButton();
        EIFSimpleRadioButton = new javax.swing.JRadioButton();
        EIFAverageRadioButton = new javax.swing.JRadioButton();
        EIFComplexRadioButton = new javax.swing.JRadioButton();
        EIData = new javax.swing.JTextField();
        EOData = new javax.swing.JTextField();
        EInqData = new javax.swing.JTextField();
        ILFData = new javax.swing.JTextField();
        EIFData = new javax.swing.JTextField();
        totalCountData = new javax.swing.JTextField();
        computeFPData = new javax.swing.JTextField();
        valueAdjustmentData = new javax.swing.JTextField();
        languageData = new javax.swing.JTextField();
        computeCodeSizeData = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        computeFPButton.setText("Compute FP");
        computeFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeFPButtonActionPerformed(evt);
            }
        });

        valueAdjustmentButton.setText("Value Adjustment");
        valueAdjustmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueAdjustmentButtonActionPerformed(evt);
            }
        });

        computeCodeSizeButton.setText("Compute Code Size");
        computeCodeSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeCodeSizeButtonActionPerformed(evt);
            }
        });

        changeLanguageButton.setText("Change Language");
        changeLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLanguageButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("External Inputs");

        jLabel4.setText("External Inquiries");

        jLabel5.setText("Internal Logical Files");

        jLabel6.setText("External Outputs");

        jLabel7.setText("External Interface Files");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Weighting Factors");

        jLabel8.setText("Total Count");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Simple   Average   Complex ");

        EIsEdit.setActionCommand("<Not Set>");
        EIsEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EIsEditKeyReleased(evt);
            }
        });

        EOsEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EOsEditKeyReleased(evt);
            }
        });

        EInqsEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EInqsEditKeyReleased(evt);
            }
        });

        ILFsEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ILFsEditKeyReleased(evt);
            }
        });

        EIFsEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EIFsEditKeyReleased(evt);
            }
        });

        EIsButtonGroup.add(EISimpleRadioButton);
        EISimpleRadioButton.setText("3");
        EISimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EISimpleRadioButtonActionPerformed(evt);
            }
        });

        EIsButtonGroup.add(EIAverageRadioButton);
        EIAverageRadioButton.setSelected(true);
        EIAverageRadioButton.setText("4");
        EIAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIAverageRadioButtonActionPerformed(evt);
            }
        });

        EIsButtonGroup.add(EIComplexRadioButton);
        EIComplexRadioButton.setText("6");
        EIComplexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIComplexRadioButtonActionPerformed(evt);
            }
        });

        EOsButtonGroup.add(EOSimpleRadioButton);
        EOSimpleRadioButton.setText("4");
        EOSimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EOSimpleRadioButtonActionPerformed(evt);
            }
        });

        EOsButtonGroup.add(EOAverageRadioButton);
        EOAverageRadioButton.setSelected(true);
        EOAverageRadioButton.setText("5");
        EOAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EOAverageRadioButtonActionPerformed(evt);
            }
        });

        EOsButtonGroup.add(EOComplexRadioButton);
        EOComplexRadioButton.setText("7");
        EOComplexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EOComplexRadioButtonActionPerformed(evt);
            }
        });

        EInqsButtonGroup.add(EInqSimpleRadioButton);
        EInqSimpleRadioButton.setText("3");
        EInqSimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EInqSimpleRadioButtonActionPerformed(evt);
            }
        });

        EInqsButtonGroup.add(EInqAverageRadioButton);
        EInqAverageRadioButton.setSelected(true);
        EInqAverageRadioButton.setText("4");
        EInqAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EInqAverageRadioButtonActionPerformed(evt);
            }
        });

        EInqsButtonGroup.add(EInqComplexRadioButton);
        EInqComplexRadioButton.setText("6");
        EInqComplexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EInqComplexRadioButtonActionPerformed(evt);
            }
        });

        ILFsButtonGroup.add(ILFSimpleRadioButton);
        ILFSimpleRadioButton.setText("7");
        ILFSimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILFSimpleRadioButtonActionPerformed(evt);
            }
        });

        ILFsButtonGroup.add(ILFAverageRadioButton);
        ILFAverageRadioButton.setSelected(true);
        ILFAverageRadioButton.setText("10");
        ILFAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILFAverageRadioButtonActionPerformed(evt);
            }
        });

        ILFsButtonGroup.add(ILFComplexRadioButton);
        ILFComplexRadioButton.setText("15");
        ILFComplexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILFComplexRadioButtonActionPerformed(evt);
            }
        });

        EIFsButtonGroup.add(EIFSimpleRadioButton);
        EIFSimpleRadioButton.setText("5");
        EIFSimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIFSimpleRadioButtonActionPerformed(evt);
            }
        });

        EIFsButtonGroup.add(EIFAverageRadioButton);
        EIFAverageRadioButton.setSelected(true);
        EIFAverageRadioButton.setText("7");
        EIFAverageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIFAverageRadioButtonActionPerformed(evt);
            }
        });

        EIFsButtonGroup.add(EIFComplexRadioButton);
        EIFComplexRadioButton.setText("10");
        EIFComplexRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIFComplexRadioButtonActionPerformed(evt);
            }
        });

        EIData.setEditable(false);
        EIData.setBackground(new java.awt.Color(238, 238, 238));

        EOData.setEditable(false);
        EOData.setBackground(new java.awt.Color(238, 238, 238));

        EInqData.setEditable(false);
        EInqData.setBackground(new java.awt.Color(238, 238, 238));

        ILFData.setEditable(false);
        ILFData.setBackground(new java.awt.Color(238, 238, 238));

        EIFData.setEditable(false);
        EIFData.setBackground(new java.awt.Color(238, 238, 238));

        totalCountData.setEditable(false);
        totalCountData.setBackground(new java.awt.Color(238, 238, 238));

        computeFPData.setEditable(false);
        computeFPData.setBackground(new java.awt.Color(238, 238, 238));

        valueAdjustmentData.setEditable(false);
        valueAdjustmentData.setBackground(new java.awt.Color(238, 238, 238));
        valueAdjustmentData.setText("0");

        languageData.setEditable(false);
        languageData.setBackground(new java.awt.Color(238, 238, 238));

        computeCodeSizeData.setEditable(false);
        computeCodeSizeData.setBackground(new java.awt.Color(238, 238, 238));

        jLabel9.setText("Current Language");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(computeCodeSizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(languageData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(computeCodeSizeData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(computeFPButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(computeFPData, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EIFsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EInqsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(ILFsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(EOsEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EIsEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(55, 55, 55))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EISimpleRadioButton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(EIAverageRadioButton)
                                                        .addGap(46, 46, 46)
                                                        .addComponent(EIComplexRadioButton))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EOSimpleRadioButton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(EOAverageRadioButton)
                                                        .addGap(46, 46, 46)
                                                        .addComponent(EOComplexRadioButton))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EInqSimpleRadioButton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(EInqAverageRadioButton)
                                                        .addGap(46, 46, 46)
                                                        .addComponent(EInqComplexRadioButton)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ILFSimpleRadioButton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(ILFAverageRadioButton))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EIFSimpleRadioButton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(EIFAverageRadioButton)))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EIFComplexRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                                        .addComponent(EIFData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(ILFComplexRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ILFData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(EOData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(EInqData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(EIData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalCountData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(valueAdjustmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valueAdjustmentData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeLanguageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EISimpleRadioButton)
                    .addComponent(EIAverageRadioButton)
                    .addComponent(EIComplexRadioButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EOSimpleRadioButton)
                    .addComponent(EOAverageRadioButton)
                    .addComponent(EOComplexRadioButton)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EOsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EOData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EInqSimpleRadioButton)
                    .addComponent(EInqAverageRadioButton)
                    .addComponent(EInqComplexRadioButton)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EInqsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EInqData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ILFSimpleRadioButton)
                    .addComponent(ILFAverageRadioButton)
                    .addComponent(ILFComplexRadioButton)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ILFsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ILFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EIFSimpleRadioButton)
                    .addComponent(EIFAverageRadioButton)
                    .addComponent(EIFComplexRadioButton)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIFsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCountData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeFPData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(computeFPButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueAdjustmentButton)
                    .addComponent(valueAdjustmentData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeCodeSizeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(computeCodeSizeButton)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeLanguageButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EISimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EISimpleRadioButtonActionPerformed
        weightingFactorEI = 3;
        complexities[0] = "simple";
    }//GEN-LAST:event_EISimpleRadioButtonActionPerformed

    private void EIAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIAverageRadioButtonActionPerformed
        weightingFactorEI = 4;
        complexities[0] = "average";
    }//GEN-LAST:event_EIAverageRadioButtonActionPerformed

    private void EIComplexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIComplexRadioButtonActionPerformed
        weightingFactorEI = 6;
        complexities[0] = "complex";
    }//GEN-LAST:event_EIComplexRadioButtonActionPerformed

    private void EOSimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EOSimpleRadioButtonActionPerformed
        weightingFactorEO = 4;
        complexities[1] = "simple";
    }//GEN-LAST:event_EOSimpleRadioButtonActionPerformed

    private void EOAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EOAverageRadioButtonActionPerformed
        weightingFactorEO = 5;
        complexities[1] = "average";
    }//GEN-LAST:event_EOAverageRadioButtonActionPerformed

    private void EOComplexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EOComplexRadioButtonActionPerformed
        weightingFactorEO = 7;
        complexities[1] = "complex";
    }//GEN-LAST:event_EOComplexRadioButtonActionPerformed

    private void EInqSimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EInqSimpleRadioButtonActionPerformed
        weightingFactorEInq = 3;
        complexities[2] = "simple";
    }//GEN-LAST:event_EInqSimpleRadioButtonActionPerformed

    private void EInqAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EInqAverageRadioButtonActionPerformed
        weightingFactorEInq = 4;
        complexities[2] = "average";
    }//GEN-LAST:event_EInqAverageRadioButtonActionPerformed

    private void EInqComplexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EInqComplexRadioButtonActionPerformed
        weightingFactorEInq = 6;
        complexities[2] = "complex";
    }//GEN-LAST:event_EInqComplexRadioButtonActionPerformed

    private void ILFSimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILFSimpleRadioButtonActionPerformed
        weightingFactorILF = 7;
        complexities[3] = "simple";
    }//GEN-LAST:event_ILFSimpleRadioButtonActionPerformed

    private void ILFAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILFAverageRadioButtonActionPerformed
        weightingFactorILF = 10;
        complexities[3] = "average";
    }//GEN-LAST:event_ILFAverageRadioButtonActionPerformed

    private void ILFComplexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILFComplexRadioButtonActionPerformed
        weightingFactorILF = 15;
        complexities[3] = "complex";
    }//GEN-LAST:event_ILFComplexRadioButtonActionPerformed

    private void EIFSimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIFSimpleRadioButtonActionPerformed
        weightingFactorEIF = 5;
        complexities[4] = "simple";
    }//GEN-LAST:event_EIFSimpleRadioButtonActionPerformed

    private void EIFAverageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIFAverageRadioButtonActionPerformed
        weightingFactorEIF = 7;
        complexities[4] = "average";
    }//GEN-LAST:event_EIFAverageRadioButtonActionPerformed

    private void EIFComplexRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIFComplexRadioButtonActionPerformed
        weightingFactorEIF = 10;
        complexities[4] = "complex";
    }//GEN-LAST:event_EIFComplexRadioButtonActionPerformed

    private void computeFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeFPButtonActionPerformed
        //EI
        if(EISimpleRadioButton.isSelected()) {
            weightingFactorEI = 3;
            complexities[0] = "simple";
            //System.out.println("EI Simple selected");
        }
        if(EIAverageRadioButton.isSelected()) {
            weightingFactorEI = 4;
            complexities[0] = "average";
        }
        if(EIComplexRadioButton.isSelected()) {
            weightingFactorEI = 6;
            complexities[0] = "complex";
        }
        //EO
        if(EOSimpleRadioButton.isSelected()) {
            weightingFactorEO = 4;
            complexities[1] = "simple";
        }
        if(EOAverageRadioButton.isSelected()) {
            weightingFactorEO = 5;
            complexities[1] = "average";
        }
        if(EOComplexRadioButton.isSelected()) {
            weightingFactorEO = 7;
            complexities[1] = "complex";
        }
        //EInq
        if(EInqSimpleRadioButton.isSelected()) {
            weightingFactorEInq = 3;
            complexities[2] = "simple";
        }
        if(EInqAverageRadioButton.isSelected()) {
            weightingFactorEInq = 4;
            complexities[2] = "average";
        }
        if(EInqComplexRadioButton.isSelected()) {
            weightingFactorEInq = 6;
            complexities[2] = "complex";
        }
        //ILF
        if(ILFSimpleRadioButton.isSelected()) {
            weightingFactorILF = 7;
            complexities[3] = "simple";
        }
        if(ILFAverageRadioButton.isSelected()) {
            weightingFactorILF = 10;
            complexities[3] = "average";
        }
        if(ILFComplexRadioButton.isSelected()) {
            weightingFactorILF = 15;
            complexities[3] = "complex";
        }
        //EIF
        if(EIFSimpleRadioButton.isSelected()) {
            weightingFactorEIF = 5;
            complexities[4] = "simple";
        }
        if(EIFAverageRadioButton.isSelected()) {
            weightingFactorEIF = 7;
            complexities[4] = "average";
        }
        if(EIFComplexRadioButton.isSelected()) {
            weightingFactorEIF = 10;
            complexities[4] = "complex";
        }
        //Compute FP
        externalInputResults = externalInput * weightingFactorEI;
        EIData.setText(Integer.toString(externalInputResults));
        
        externalOutputResults = externalOutput * weightingFactorEO;
        EOData.setText(Integer.toString(externalOutputResults));
        
        externalInquiriesResults = externalInquiries * weightingFactorEInq;
        EInqData.setText(Integer.toString(externalInquiriesResults));
        
        internalLogicalFilesResults = internalLogicalFiles * weightingFactorILF;
        ILFData.setText(Integer.toString(internalLogicalFilesResults));
        
        externalInterfaceFilesResults = externalInterfaceFiles * weightingFactorEIF;
        EIFData.setText(Integer.toString(externalInterfaceFilesResults));
        
        //Sum of all EI, EO, ...
        totalCount = externalInputResults + externalOutputResults + externalInquiriesResults + internalLogicalFilesResults + externalInterfaceFilesResults;
        totalCountData.setText(Integer.toString(totalCount));
        
        //Value adjustment sum
        valueAdjustmentSum = Integer.parseInt(valueAdjustmentData.getText());
        
        //Compute FP w/ total count and valueadjustment
        computeFP = totalCount * (0.65 + (0.01 * valueAdjustmentSum));
        String formattedFP = df.format(computeFP);
        computeFPData.setText(formattedFP);
    }//GEN-LAST:event_computeFPButtonActionPerformed

    private void EIsEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EIsEditKeyReleased
        //Validate values are non-negative integers
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            externalInput = Integer.parseInt(EIsEdit.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            EIsEdit.setText(Integer.toString(externalInput));
        }
    }//GEN-LAST:event_EIsEditKeyReleased

    private void EOsEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EOsEditKeyReleased
        //Validate values are non-negative integers
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            externalOutput = Integer.parseInt(EOsEdit.getText());
            //System.out.println("External Output" + externalInput);
        }
        else {
            //System.out.println("what character is this? " + character);
            EOsEdit.setText(Integer.toString(externalOutput));
        }
    }//GEN-LAST:event_EOsEditKeyReleased

    private void EInqsEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EInqsEditKeyReleased
        //Validate values are non-negative integers
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            externalInquiries = Integer.parseInt(EInqsEdit.getText());
            //System.out.println("External Inquiries" + externalInput);
        }
        else {
            //System.out.println("what character is this? " + character);
            EInqsEdit.setText(Integer.toString(externalInquiries));
        }
    }//GEN-LAST:event_EInqsEditKeyReleased

    private void ILFsEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ILFsEditKeyReleased
        //Validate values are non-negative integers
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            internalLogicalFiles = Integer.parseInt(ILFsEdit.getText());
            //System.out.println("External Inquiries" + externalInput);
        }
        else {
            ILFsEdit.setText(Integer.toString(internalLogicalFiles));
        }
        
    }//GEN-LAST:event_ILFsEditKeyReleased

    private void EIFsEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EIFsEditKeyReleased
        //Validate values are non-negative integers
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            externalInterfaceFiles = Integer.parseInt(EIFsEdit.getText());
        }
        else {
            EIFsEdit.setText(Integer.toString(externalInterfaceFiles));
        }
    }//GEN-LAST:event_EIFsEditKeyReleased

    private void valueAdjustmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueAdjustmentButtonActionPerformed
        // TODO add your handling code here:
        ValueAdjustmentWindow va = new ValueAdjustmentWindow(this, valueAdjustmentList);
        va.setVisible(true);
        va.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_valueAdjustmentButtonActionPerformed

    private void changeLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLanguageButtonActionPerformed
        //open language dialogue window
        Language language = new Language(this, mainframe);
        language.setVisible(true);
        language.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_changeLanguageButtonActionPerformed

    private void computeCodeSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeCodeSizeButtonActionPerformed
        // TODO add your handling code here:
        if(language.equals("Assembler")) {
            codeSize = 209 * computeFP;
        }
        if(language.equals("Ada 95")) {
            codeSize = 154 * computeFP;
        }
        if(language.equals("C")) {
            codeSize = 148 * computeFP;
        }
        if(language.equals("C++")) {
            codeSize = 59 * computeFP;
        }
        if(language.equals("C#")) {
            codeSize = 58 * computeFP;
        }
        if(language.equals("COBOL")) {
            codeSize = 80 * computeFP;
        }
        if(language.equals("FORTRAN")) {
            codeSize = 90 * computeFP;
        }
        if(language.equals("HTML")) {
            codeSize = 43 * computeFP;
        }
        if(language.equals("Java")) {
            codeSize = 55 * computeFP;
        }
        if(language.equals("JavaScript")) {
            codeSize = 54 * computeFP;
        }
        if(language.equals("VBScript")) {
            codeSize = 38 * computeFP;
        }
        if(language.equals("Visual Basic")) {
            codeSize = 50 * computeFP;
        }
        String formattedCodeSize = df.format(codeSize);
        computeCodeSizeData.setText(formattedCodeSize);
        //computeCodeSizeData.setText(Double.toString(codeSize));
    }//GEN-LAST:event_computeCodeSizeButtonActionPerformed
    
    public void complexities(String [] arr) {
        if(arr[0].equals("simple")){
            EISimpleRadioButton.setSelected(true);
            weightingFactorEI = 3;
        }
        else if(arr[0].equals("average")) {
            EIAverageRadioButton.setSelected(true);
            weightingFactorEI = 4;
        }
        else if(arr[0].equals("complex")) {
            EIComplexRadioButton.setSelected(true);
            weightingFactorEI = 6;
        }
        
        if(arr[1].equals("simple")){
            EOSimpleRadioButton.setSelected(true);
            weightingFactorEO = 4;
        }
        else if(arr[1].equals("average")) {
            EOAverageRadioButton.setSelected(true);
            weightingFactorEO = 5;
        }
        else if(arr[1].equals("complex")) {
            EOComplexRadioButton.setSelected(true);
            weightingFactorEO = 7;
        }
        
        if(arr[2].equals("simple")){
            EInqSimpleRadioButton.setSelected(true);
            weightingFactorEInq = 3;
        }
        else if(arr[2].equals("average")) {
            EInqAverageRadioButton.setSelected(true);
            weightingFactorEInq = 4;
        }
        else if(arr[2].equals("complex")) {
            EInqComplexRadioButton.setSelected(true);
            weightingFactorEInq = 6;
        }
        
        if(arr[3].equals("simple")){
            ILFSimpleRadioButton.setSelected(true);
            weightingFactorILF = 7;
        }
        else if(arr[3].equals("average")) {
            ILFAverageRadioButton.setSelected(true);
            weightingFactorILF = 10;
        }
        else if(arr[3].equals("complex")) {
            ILFComplexRadioButton.setSelected(true);
            weightingFactorILF = 15;
        }
        
        if(arr[4].equals("simple")){
            EIFSimpleRadioButton.setSelected(true);
            weightingFactorEIF = 5;
        }
        else if(arr[4].equals("average")) {
            EIFAverageRadioButton.setSelected(true);
            weightingFactorEIF = 7;
        }
        else if(arr[4].equals("complex")) {
            EIFComplexRadioButton.setSelected(true);
            weightingFactorEIF = 10;
        }
    }
    
    
    public String getNameOfPane() {
        return nameOfPane;
    }

    public void setNameOfPane(String nameOfPane) {
        this.nameOfPane = nameOfPane;
    }

    public int getExternalInput() {
        return externalInput;
    }

    public void setExternalInput(int externalInput) {
        this.externalInput = externalInput;
    }

    public int getExternalOutput() {
        return externalOutput;
    }

    public void setExternalOutput(int externalOutput) {
        this.externalOutput = externalOutput;
    }

    public int getExternalInquiries() {
        return externalInquiries;
    }

    public void setExternalInquiries(int externalInquiries) {
        this.externalInquiries = externalInquiries;
    }

    public int getInternalLogicalFiles() {
        return internalLogicalFiles;
    }

    public void setInternalLogicalFiles(int internalLogicalFiles) {
        this.internalLogicalFiles = internalLogicalFiles;
    }

    public int getExternalInterfaceFiles() {
        return externalInterfaceFiles;
    }

    public void setExternalInterfaceFiles(int externalInterfaceFiles) {
        this.externalInterfaceFiles = externalInterfaceFiles;
    }

    public int getWeightingFactorEI() {
        return weightingFactorEI;
    }

    public void setWeightingFactorEI(int weightingFactorEI) {
        this.weightingFactorEI = weightingFactorEI;
    }

    public int getWeightingFactorEO() {
        return weightingFactorEO;
    }

    public void setWeightingFactorEO(int weightingFactorEO) {
        this.weightingFactorEO = weightingFactorEO;
    }

    public int getWeightingFactorEInq() {
        return weightingFactorEInq;
    }

    public void setWeightingFactorEInq(int weightingFactorEInq) {
        this.weightingFactorEInq = weightingFactorEInq;
    }

    public int getWeightingFactorILF() {
        return weightingFactorILF;
    }

    public void setWeightingFactorILF(int weightingFactorILF) {
        this.weightingFactorILF = weightingFactorILF;
    }

    public int getWeightingFactorEIF() {
        return weightingFactorEIF;
    }

    public void setWeightingFactorEIF(int weightingFactorEIF) {
        this.weightingFactorEIF = weightingFactorEIF;
    }

    public int getExternalInputResults() {
        return externalInputResults;
    }

    public void setExternalInputResults(int externalInputResults) {
        this.externalInputResults = externalInputResults;
    }

    public int getExternalOutputResults() {
        return externalOutputResults;
    }

    public void setExternalOutputResults(int externalOutputResults) {
        this.externalOutputResults = externalOutputResults;
    }

    public int getExternalInquiriesResults() {
        return externalInquiriesResults;
    }

    public void setExternalInquiriesResults(int externalInquiriesResults) {
        this.externalInquiriesResults = externalInquiriesResults;
    }

    public int getInternalLogicalFilesResults() {
        return internalLogicalFilesResults;
    }

    public void setInternalLogicalFilesResults(int internalLogicalFilesResults) {
        this.internalLogicalFilesResults = internalLogicalFilesResults;
    }

    public int getExternalInterfaceFilesResults() {
        return externalInterfaceFilesResults;
    }

    public void setExternalInterfaceFilesResults(int externalInterfaceFilesResults) {
        this.externalInterfaceFilesResults = externalInterfaceFilesResults;
    }

    public int getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(int totalCount) {
        this.totalCount = totalCount;
    }

    public double getComputeFP() {
        return computeFP;
    }

    public void setComputeFP(double computeFP) {
        this.computeFP = computeFP;
    }

    public int getValueAdjustmentSum() {
        return valueAdjustmentSum;
    }

    public void setValueAdjustmentSum(int valueAdjustmentSum) {
        this.valueAdjustmentSum = valueAdjustmentSum;
        valueAdjustmentData.setText(Integer.toString(valueAdjustmentSum));
    }

    public double getCodeSize() {
        return codeSize;
    }

    public void setCodeSize(double codeSize) {
        this.codeSize = codeSize;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }
    
    public void setLanguageTextField(String language){
        this.languageData.setText(language);
    }

    public int[] getValueAdjustmentList() {
        return valueAdjustmentList;
    }

    public void setValueAdjustmentList(int[] valueAdjustmentList) {
        this.valueAdjustmentList = valueAdjustmentList;
    }

    public String[] getComplexities() {
        return complexities;
    }

    public void setComplexities(String[] complexities) {
        this.complexities = complexities;
    }

    //
    public void setEIAverageRadioButton(boolean m) {
        this.EIAverageRadioButton.setSelected(m);
    }
    
    public void setEIComplexRadioButton(boolean m) {
        this.EIComplexRadioButton.setSelected(m);
    }

    public String getEIData() {
        return EIData.getText();
    }

    public void setEIData(String EIData) {
        this.EIData.setText(EIData);
    }

    public void setEIFAverageRadioButton(boolean m) {
        this.EIFAverageRadioButton.setSelected(m);
    }

    public void setEIFComplexRadioButton(boolean m) {
        this.EIFComplexRadioButton.setSelected(m);
    }

    public String getEIFData() {
        return EIFData.getText();
    }

    public void setEIFData(String EIFData) {
        this.EIFData.setText(EIFData);
    }

    public void setEIFSimpleRadioButton(boolean m) {
        this.EIFSimpleRadioButton.setSelected(m);
    }

    public String getEIFsEdit() {
        return EIFsEdit.getText();
    }

    public void setEIFsEdit(String EIFsEdit) {
        this.EIFsEdit.setText(EIFsEdit);
    }

    public void setEISimpleRadioButton(boolean m) {
        this.EISimpleRadioButton.setSelected(m);
    }

    public void setEInqAverageRadioButton(boolean m) {
        this.EInqAverageRadioButton.setSelected(m);
    }

    public void setEInqComplexRadioButton(boolean m) {
        this.EInqComplexRadioButton.setSelected(m);
    }

    public String getEInqData() {
        return EInqData.getText();
    }

    public void setEInqData(String EInqData) {
        this.EInqData.setText(EInqData);
    }

    public void setEInqSimpleRadioButton(boolean m) {
        this.EInqSimpleRadioButton.setSelected(m);
    }

    public String getEInqsEdit() {
        return EInqsEdit.getText();
    }

    public void setEInqsEdit(String EInqsEdit) {
        this.EInqsEdit.setText(EInqsEdit);
    }

    public String getEIsEdit() {
        return EIsEdit.getText();
    }

    public void setEIsEdit(String EIsEdit) {
        this.EIsEdit.setText(EIsEdit);
    }

    public void setEOAverageRadioButton(boolean m) {
        this.EOAverageRadioButton.setSelected(m);
    }

    public void setEOComplexRadioButton(boolean m) {
        this.EOComplexRadioButton.setSelected(m);
    }

    public String getEOData() {
        return EOData.getText();
    }

    public void setEOData(String EOData) {
        this.EOData.setText(EOData);
    }

    public void setEOSimpleRadioButton(boolean m) {
        this.EOSimpleRadioButton.setSelected(m);
    }

    public String getEOsEdit() {
        return EOsEdit.getText();
    }

    public void setEOsEdit(String EOsEdit) {
        this.EOsEdit.setText(EOsEdit);
    }

    public void setILFAverageRadioButton(boolean m) {
        this.ILFAverageRadioButton.setSelected(m);
    }
    
    public void setILFComplexRadioButton(boolean m) {
        this.ILFComplexRadioButton.setSelected(m);
    }

    public String getILFData() {
        return ILFData.getText();
    }

    public void setILFData(String ILFData) {
        this.ILFData.setText(ILFData);
    }
    
    public void setILFSimpleRadioButton(boolean m) {
        this.ILFSimpleRadioButton.setSelected(m);
    }

    public String getILFsEdit() {
        return ILFsEdit.getText();
    }

    public void setILFsEdit(String ILFsEdit) {
        this.ILFsEdit.setText(ILFsEdit);
    }
    
    public String getComputeCodeSizeData() {
        return computeCodeSizeData.getText();
    }

    public void setComputeCodeSizeData(String computeCodeSizeData) {
        this.computeCodeSizeData.setText(computeCodeSizeData);
    }

    public String getComputeFPData() {
        return computeFPData.getText();
    }

    public void setComputeFPData(String computeFPData) {
        this.computeFPData.setText(computeFPData);
    }
    

    public String getLanguageData() {
        return languageData.getText();
    }
    
    public void setLanguageData(String languageData) {
        //this.languageData = languageData;
        this.languageData.setText(languageData);
    }
    
    public String getTotalCountData() {
        return totalCountData.getText();
    }

    public void setTotalCountData(String totalCountData) {
        this.totalCountData.setText(totalCountData);
    }

    public String getValueAdjustmentData() {
        return valueAdjustmentData.getText();
    }

    public void setValueAdjustmentData(String valueAdjustmentData) {
        this.valueAdjustmentData.setText(valueAdjustmentData);
    }
    
    public void printValueAdjustmentList() {
        for(int i=0; i<valueAdjustmentList.length; i++) {
            System.out.print(valueAdjustmentList[i] + ",");
        }
    }

    @Override
    public String toString() {
        return "Pane{" + "nameOfPane=" + nameOfPane + ", externalInput=" + externalInput + ", externalOutput=" + externalOutput + ", externalInquiries=" + externalInquiries + ", internalLogicalFiles=" + internalLogicalFiles + ", externalInterfaceFiles=" + externalInterfaceFiles + ", weightingFactorEI=" + weightingFactorEI + ", weightingFactorEO=" + weightingFactorEO + ", weightingFactorEInq=" + weightingFactorEInq + ", weightingFactorILF=" + weightingFactorILF + ", weightingFactorEIF=" + weightingFactorEIF + ", externalInputResults=" + externalInputResults + ", externalOutputResults=" + externalOutputResults + ", externalInquiriesResults=" + externalInquiriesResults + ", internalLogicalFilesResults=" + internalLogicalFilesResults + ", externalInterfaceFilesResults=" + externalInterfaceFilesResults + ", totalCount=" + totalCount + ", computeFP=" + computeFP + ", valueAdjustmentSum=" + valueAdjustmentSum + ", codeSize=" + codeSize + ", language=" + language + ", valueAdjustmentList=" + valueAdjustmentList.toString() + ", complexities=" + complexities + '}';
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EIAverageRadioButton;
    private javax.swing.JRadioButton EIComplexRadioButton;
    private javax.swing.JTextField EIData;
    private javax.swing.JRadioButton EIFAverageRadioButton;
    private javax.swing.JRadioButton EIFComplexRadioButton;
    private javax.swing.JTextField EIFData;
    private javax.swing.JRadioButton EIFSimpleRadioButton;
    private javax.swing.ButtonGroup EIFsButtonGroup;
    private javax.swing.JTextField EIFsEdit;
    private javax.swing.JRadioButton EISimpleRadioButton;
    private javax.swing.JRadioButton EInqAverageRadioButton;
    private javax.swing.JRadioButton EInqComplexRadioButton;
    private javax.swing.JTextField EInqData;
    private javax.swing.JRadioButton EInqSimpleRadioButton;
    private javax.swing.ButtonGroup EInqsButtonGroup;
    private javax.swing.JTextField EInqsEdit;
    private javax.swing.ButtonGroup EIsButtonGroup;
    private javax.swing.JTextField EIsEdit;
    private javax.swing.JRadioButton EOAverageRadioButton;
    private javax.swing.JRadioButton EOComplexRadioButton;
    private javax.swing.JTextField EOData;
    private javax.swing.JRadioButton EOSimpleRadioButton;
    private javax.swing.ButtonGroup EOsButtonGroup;
    private javax.swing.JTextField EOsEdit;
    private javax.swing.JRadioButton ILFAverageRadioButton;
    private javax.swing.JRadioButton ILFComplexRadioButton;
    private javax.swing.JTextField ILFData;
    private javax.swing.JRadioButton ILFSimpleRadioButton;
    private javax.swing.ButtonGroup ILFsButtonGroup;
    private javax.swing.JTextField ILFsEdit;
    private javax.swing.JButton changeLanguageButton;
    private javax.swing.JButton computeCodeSizeButton;
    private javax.swing.JTextField computeCodeSizeData;
    private javax.swing.JButton computeFPButton;
    private javax.swing.JTextField computeFPData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField languageData;
    private javax.swing.JTextField totalCountData;
    private javax.swing.JButton valueAdjustmentButton;
    private javax.swing.JTextField valueAdjustmentData;
    // End of variables declaration//GEN-END:variables
}
