/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package metricssuite;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author school
 */
public class Language extends javax.swing.JFrame {

    private MainFrame m;
    private Pane p;
    private String languageSelected = "";
    private int window;
    /** Creates new form Language */
    public Language() {
        initComponents();
    }
    
    public Language(MainFrame m) {
        initComponents();
        this.m = m;
        window = 1;
    }
    public Language(Pane p, MainFrame m) {
        initComponents();
        this.p = p;
        this.m = m;
        window = 2;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        assembler = new javax.swing.JCheckBox();
        ada95 = new javax.swing.JCheckBox();
        cprogram = new javax.swing.JCheckBox();
        cplusplus = new javax.swing.JCheckBox();
        csharp = new javax.swing.JCheckBox();
        cobol = new javax.swing.JCheckBox();
        fortran = new javax.swing.JCheckBox();
        html = new javax.swing.JCheckBox();
        javaprogram = new javax.swing.JCheckBox();
        javascript = new javax.swing.JCheckBox();
        vbScript = new javax.swing.JCheckBox();
        visualbasic = new javax.swing.JCheckBox();
        doneJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(assembler);
        assembler.setText("Assembler");

        buttonGroup1.add(ada95);
        ada95.setText("Ada 95");

        buttonGroup1.add(cprogram);
        cprogram.setText("C");

        buttonGroup1.add(cplusplus);
        cplusplus.setText("C++");
        cplusplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cplusplusActionPerformed(evt);
            }
        });

        buttonGroup1.add(csharp);
        csharp.setText("C#");

        buttonGroup1.add(cobol);
        cobol.setText("COBOL");

        buttonGroup1.add(fortran);
        fortran.setText("FORTRAN");

        buttonGroup1.add(html);
        html.setText("HTML");

        buttonGroup1.add(javaprogram);
        javaprogram.setText("Java");

        buttonGroup1.add(javascript);
        javascript.setText("JavaScript");

        buttonGroup1.add(vbScript);
        vbScript.setText("VBScript");

        buttonGroup1.add(visualbasic);
        visualbasic.setText("Visual Basic");

        doneJButton.setText("Done");
        doneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select one language");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(visualbasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vbScript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(javascript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(javaprogram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(html, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fortran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cobol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(csharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cplusplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cprogram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ada95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assembler, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(doneJButton)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(doneJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(assembler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ada95)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cprogram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cplusplus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csharp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cobol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fortran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(html)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaprogram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javascript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vbScript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visualbasic)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneJButtonActionPerformed
        //m.setLanguage("Assembler");
        languageSelection();
        String currentDirectory = System.getProperty("user.home");
        if(window == 1) {
            
            //File outputFile = new File(currentDirectory + "/src/Resources/language.txt");
//            File outputFile = new File("src/Recources/language.txt");
//            FileWriter fWriter = null;	
//            try {
//                fWriter = new FileWriter(outputFile);
//            } catch (IOException ex) {
//            Logger.getLogger(Language.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            PrintWriter pWriter = new PrintWriter(fWriter);
//            pWriter.print(languageSelected);
//            pWriter.close();


//Modified version using textfile
            File outputFile = new File(currentDirectory + "/language.txt");
            //File outputFile = new File("src/Recources/language.txt");
            FileWriter fWriter = null;	
            try {
                fWriter = new FileWriter(outputFile);
            } catch (IOException ex) {
            Logger.getLogger(Language.class.getName()).log(Level.SEVERE, null, ex);
            }
            PrintWriter pWriter = new PrintWriter(fWriter);
            pWriter.print(languageSelected);
            pWriter.close();



/******/

//Help from: https://owlcation.com/stem/Java-Examples-Application-Properties-Persisted-as-Simple-Text-File
//            Properties savedLanguage = new Properties();
//            savedLanguage.setProperty("Language", languageSelected);
//            
//            Path PropertyFile = Paths.get("Language.Properties");
//            try
//            {
//                Writer PropWriter = Files.newBufferedWriter(PropertyFile);
//                savedLanguage.store(PropWriter, "Language Properties");
//                PropWriter.close();
//            }
//            catch(IOException Ex) {
//                System.out.println("IO Exception :" + Ex.getMessage());
//            }
//            
            
            
        }
        else {
            m.setLanguage(languageSelected);
            m.setProjectLanguage(languageSelected);
            p.setLanguage(languageSelected);
            p.setLanguageTextField(languageSelected);
        }
        this.dispose();
    }//GEN-LAST:event_doneJButtonActionPerformed

    private void cplusplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cplusplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cplusplusActionPerformed

    //a function depending which window was called (pane or mainframe)
    public void languageSelection() {
        if(assembler.isSelected()) {
            languageSelected = "Assembler";
        }
        else if(ada95.isSelected()) {
            languageSelected = "Ada 95";
        }
        else if(cprogram.isSelected()) {
            languageSelected = "C";
        }
        else if(cplusplus.isSelected()) {
            languageSelected = "C++";
        }
        else if(csharp.isSelected()) {
            languageSelected = "C#";
        }
        else if(cobol.isSelected()) {
            languageSelected = "COBOL";
        }
        else if(fortran.isSelected()) {
            languageSelected = "FORTRAN";
        }
        else if(html.isSelected()) {
            languageSelected = "HTML";
        }
        else if(javaprogram.isSelected()) {
            languageSelected = "Java";
        }
        else if(javascript.isSelected()) {
            languageSelected = "JavaScript";
        }
        else if(vbScript.isSelected()) {
            languageSelected = "VBScript";
        }
        else if(visualbasic.isSelected()) {
            languageSelected = "Visual Basic";
        }
        else
            languageSelected = "None";
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Language().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ada95;
    private javax.swing.JCheckBox assembler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cobol;
    private javax.swing.JCheckBox cplusplus;
    private javax.swing.JCheckBox cprogram;
    private javax.swing.JCheckBox csharp;
    private javax.swing.JButton doneJButton;
    private javax.swing.JCheckBox fortran;
    private javax.swing.JCheckBox html;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox javaprogram;
    private javax.swing.JCheckBox javascript;
    private javax.swing.JCheckBox vbScript;
    private javax.swing.JCheckBox visualbasic;
    // End of variables declaration//GEN-END:variables

}
