/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metricssuite;

import javax.swing.JButton;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author school
 */
public class UseCasePointsPane extends javax.swing.JPanel {

    ///COMMENT
    private int UUCW_simple = 0;
    private int UUCW_average = 0;
    private int UUCW_complex = 0;
    private int UUCW_total = 0;
    
    private int UAW_simple = 0;
    private int UAW_average = 0;
    private int UAW_complex = 0;
    private int UAW_total = 0;
    
    private int UUCP = 0;
    
    //tcf array
    private int [] tcfArray = new int[13];
    private double tcfSum = 0;
    //ecf array
    private int [] ecfArray = new int[8];
    private double ecfSum = 0;

    private int PF = 20;
    private int LOC_pm = 700;
    private int LOC_UCP = 100;
    
    private double UCP_Total = 0;
    private double estimatedHours = 0;
    private double estimatedLOC = 0;
    private double estimatedPM = 0;
    
    /**
     * Creates new form UseCasePane
     */
    public UseCasePointsPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tcf_Button = new javax.swing.JButton();
        ecf_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uucw_simple_textfield = new javax.swing.JTextField();
        uucw_average_textfield = new javax.swing.JTextField();
        uucw_complex_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uaw_simple_textfield = new javax.swing.JTextField();
        uaw_average_textfield = new javax.swing.JTextField();
        uaw_complex_textfield = new javax.swing.JTextField();
        uucw_total_textfield = new javax.swing.JTextField();
        compute_UUCP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tcf_total_textfield = new javax.swing.JTextField();
        uaw_total_textfield = new javax.swing.JTextField();
        loc_pm_textfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        productivityFactor_textfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        loc_ucp_textfield = new javax.swing.JTextField();
        ucp_textfield = new javax.swing.JTextField();
        estimatedHours_textfield = new javax.swing.JTextField();
        estimatedLOC_textfield = new javax.swing.JTextField();
        estimatedPM_textfield = new javax.swing.JTextField();
        ucp_button = new javax.swing.JButton();
        estimatedHours_button = new javax.swing.JButton();
        estimatedLOC_button = new javax.swing.JButton();
        estimatedPM_button = new javax.swing.JButton();
        ecf_total_textfield = new javax.swing.JTextField();
        value_UUCP_textfield = new javax.swing.JTextField();

        tcf_Button.setText("Technical Complexity Factor");
        tcf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcf_ButtonActionPerformed(evt);
            }
        });

        ecf_Button.setText("Environment Complexity Factor");
        ecf_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecf_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("UUCW");

        jLabel2.setText("Simple Use Cases");

        jLabel3.setText("Average Use Cases");

        jLabel4.setText("Complex Use Cases");

        uucw_simple_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uucw_simple_textfieldKeyReleased(evt);
            }
        });

        uucw_average_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uucw_average_textfieldKeyReleased(evt);
            }
        });

        uucw_complex_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uucw_complex_textfieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("UAW");

        jLabel6.setText("Simple Actors");

        jLabel7.setText("Average Actors");

        jLabel8.setText("Complex Actors");

        uaw_simple_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uaw_simple_textfieldKeyReleased(evt);
            }
        });

        uaw_average_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uaw_average_textfieldKeyReleased(evt);
            }
        });

        uaw_complex_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uaw_complex_textfieldKeyReleased(evt);
            }
        });

        uucw_total_textfield.setEditable(false);
        uucw_total_textfield.setBackground(new java.awt.Color(238, 238, 238));

        compute_UUCP.setText("Compute UUCP");
        compute_UUCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compute_UUCPActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Productivity Factor");

        tcf_total_textfield.setEditable(false);
        tcf_total_textfield.setBackground(new java.awt.Color(238, 238, 238));

        uaw_total_textfield.setEditable(false);
        uaw_total_textfield.setBackground(new java.awt.Color(238, 238, 238));

        loc_pm_textfield.setText("700");
        loc_pm_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loc_pm_textfieldKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("LOC/pm");

        productivityFactor_textfield.setText("20");
        productivityFactor_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productivityFactor_textfieldKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("LOC/UCP");

        loc_ucp_textfield.setText("100");
        loc_ucp_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loc_ucp_textfieldKeyReleased(evt);
            }
        });

        ucp_textfield.setBackground(new java.awt.Color(238, 238, 238));

        estimatedHours_textfield.setBackground(new java.awt.Color(238, 238, 238));

        estimatedLOC_textfield.setBackground(new java.awt.Color(238, 238, 238));

        estimatedPM_textfield.setBackground(new java.awt.Color(238, 238, 238));

        ucp_button.setText("Total UCP");
        ucp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucp_buttonActionPerformed(evt);
            }
        });

        estimatedHours_button.setText("Estimated Hours");
        estimatedHours_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedHours_buttonActionPerformed(evt);
            }
        });

        estimatedLOC_button.setText("Estimated LOC");
        estimatedLOC_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedLOC_buttonActionPerformed(evt);
            }
        });

        estimatedPM_button.setText("Estimated PM");
        estimatedPM_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedPM_buttonActionPerformed(evt);
            }
        });

        ecf_total_textfield.setEditable(false);
        ecf_total_textfield.setBackground(new java.awt.Color(238, 238, 238));

        value_UUCP_textfield.setEditable(false);
        value_UUCP_textfield.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(loc_ucp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loc_pm_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productivityFactor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ecf_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ecf_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tcf_Button)
                                .addGap(18, 18, 18)
                                .addComponent(tcf_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ucp_button, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(ucp_textfield))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimatedHours_button, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(estimatedHours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimatedLOC_button)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(estimatedLOC_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimatedPM_button)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(estimatedPM_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(uucw_complex_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(uucw_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uucw_simple_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(uucw_average_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(uaw_complex_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(uaw_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uaw_simple_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(uaw_average_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compute_UUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(value_UUCP_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uucw_complex_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uucw_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uucw_simple_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uucw_average_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(compute_UUCP))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(value_UUCP_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uaw_average_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uaw_simple_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uaw_complex_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uaw_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productivityFactor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tcf_Button)
                    .addComponent(tcf_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loc_pm_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loc_ucp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ecf_Button)
                        .addComponent(ecf_total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedHours_button)
                    .addComponent(ucp_button)
                    .addComponent(estimatedLOC_button)
                    .addComponent(estimatedPM_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ucp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estimatedHours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estimatedLOC_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(estimatedPM_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void compute_UUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compute_UUCPActionPerformed
        //Compute UUCW
        UUCW_total = (UUCW_simple * 5) + (UUCW_average * 10) + (UUCW_complex * 15);
        System.out.println("UUCW simple = " + UUCW_simple);
        System.out.println("UUCW average = " + UUCW_average);
        System.out.println("UUCW complex = " + UUCW_complex);
        uucw_total_textfield.setText(Integer.toString(UUCW_total));
        
        //Compute UAW
        UAW_total = (UAW_simple * 1) + (UAW_average * 2) + (UAW_complex * 3);
        System.out.println("UAW simple = " + UAW_simple);
        System.out.println("UAW average = " + UAW_average);
        System.out.println("UAW complex = " + UAW_complex);
        uaw_total_textfield.setText(Integer.toString(UAW_total));
        //Compute UUCP
        UUCP = UUCW_total + UAW_total;
        value_UUCP_textfield.setText(Integer.toString(UUCP));
    }//GEN-LAST:event_compute_UUCPActionPerformed

    private void uucw_simple_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uucw_simple_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UUCW_simple = Integer.parseInt(uucw_simple_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uucw_simple_textfield.setText(Integer.toString(UUCW_simple));
        }
    }//GEN-LAST:event_uucw_simple_textfieldKeyReleased

    private void uucw_average_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uucw_average_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UUCW_average = Integer.parseInt(uucw_average_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uucw_average_textfield.setText(Integer.toString(UUCW_average));
        }
    }//GEN-LAST:event_uucw_average_textfieldKeyReleased

    private void uucw_complex_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uucw_complex_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UUCW_complex = Integer.parseInt(uucw_complex_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uucw_complex_textfield.setText(Integer.toString(UUCW_complex));
        }
    }//GEN-LAST:event_uucw_complex_textfieldKeyReleased

    private void uaw_simple_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uaw_simple_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UAW_simple = Integer.parseInt(uaw_simple_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uaw_simple_textfield.setText(Integer.toString(UAW_simple));
        }
    }//GEN-LAST:event_uaw_simple_textfieldKeyReleased

    private void uaw_average_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uaw_average_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UAW_average = Integer.parseInt(uaw_average_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uaw_average_textfield.setText(Integer.toString(UAW_average));
        }
    }//GEN-LAST:event_uaw_average_textfieldKeyReleased

    private void uaw_complex_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uaw_complex_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            UAW_complex = Integer.parseInt(uaw_complex_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            uaw_complex_textfield.setText(Integer.toString(UAW_complex));
        }
    }//GEN-LAST:event_uaw_complex_textfieldKeyReleased

    private void tcf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcf_ButtonActionPerformed
        TechnicalComplexityFactor tcf = new TechnicalComplexityFactor(this, tcfArray);
        tcf.setVisible(true);
        tcf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_tcf_ButtonActionPerformed

    private void productivityFactor_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productivityFactor_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            PF = Integer.parseInt(productivityFactor_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            productivityFactor_textfield.setText(Integer.toString(PF));
        }
    }//GEN-LAST:event_productivityFactor_textfieldKeyReleased

    private void loc_pm_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loc_pm_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            LOC_pm = Integer.parseInt(loc_pm_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            loc_pm_textfield.setText(Integer.toString(LOC_pm));
        }
    }//GEN-LAST:event_loc_pm_textfieldKeyReleased

    private void loc_ucp_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loc_ucp_textfieldKeyReleased
        char character = evt.getKeyChar();
        int code = evt.getKeyCode();
        if((code >= 48 && code <=57) || code == 8 || code == 127 || code == 37 || code == 38 || code == 39 || code == 40 ){
            LOC_UCP = Integer.parseInt(loc_ucp_textfield.getText());
            //System.out.println("External Input" + externalInput);
        }
        else{
            //System.out.println("what character is this? " + character);
            loc_ucp_textfield.setText(Integer.toString(LOC_UCP));
        }
    }//GEN-LAST:event_loc_ucp_textfieldKeyReleased

    private void ecf_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecf_ButtonActionPerformed
        //ecf button
        EnvironmentComplexityFactor ecf = new EnvironmentComplexityFactor(this, ecfArray);
        ecf.setVisible(true);
        ecf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ecf_ButtonActionPerformed

    private void ucp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucp_buttonActionPerformed
        UCP_Total = tcfSum * ecfSum * UUCP * PF;
        ucp_textfield.setText(Double.toString(UCP_Total));
    }//GEN-LAST:event_ucp_buttonActionPerformed

    private void estimatedHours_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedHours_buttonActionPerformed
        estimatedHours = UCP_Total * PF;
        estimatedHours_textfield.setText(Double.toString(estimatedHours));
    }//GEN-LAST:event_estimatedHours_buttonActionPerformed

    private void estimatedLOC_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedLOC_buttonActionPerformed
        estimatedLOC = LOC_UCP * UCP_Total;
        estimatedLOC_textfield.setText(Double.toString(estimatedLOC));
    }//GEN-LAST:event_estimatedLOC_buttonActionPerformed

    private void estimatedPM_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedPM_buttonActionPerformed
        estimatedPM = LOC_pm * estimatedLOC;
        estimatedPM_textfield.setText(Double.toString(estimatedPM));
    }//GEN-LAST:event_estimatedPM_buttonActionPerformed

    public int getUUCW_simple() {
        return UUCW_simple;
    }

    public void setUUCW_simple(int UUCW_simple) {
        this.UUCW_simple = UUCW_simple;
    }

    public int getUUCW_average() {
        return UUCW_average;
    }

    public void setUUCW_average(int UUCW_average) {
        this.UUCW_average = UUCW_average;
    }

    public int getUUCW_complex() {
        return UUCW_complex;
    }

    public void setUUCW_complex(int UUCW_complex) {
        this.UUCW_complex = UUCW_complex;
    }

    public int getUUCW_total() {
        return UUCW_total;
    }

    public void setUUCW_total(int UUCW_total) {
        this.UUCW_total = UUCW_total;
    }

    public int getUAW_simple() {
        return UAW_simple;
    }

    public void setUAW_simple(int UAW_simple) {
        this.UAW_simple = UAW_simple;
    }

    public int getUAW_average() {
        return UAW_average;
    }

    public void setUAW_average(int UAW_average) {
        this.UAW_average = UAW_average;
    }

    public int getUAW_complex() {
        return UAW_complex;
    }

    public void setUAW_complex(int UAW_complex) {
        this.UAW_complex = UAW_complex;
    }

    public int getUAW_total() {
        return UAW_total;
    }

    public void setUAW_total(int UAW_total) {
        this.UAW_total = UAW_total;
    }

    public int getUUCP() {
        return UUCP;
    }

    public void setUUCP(int UUCP) {
        this.UUCP = UUCP;
    }

    public JButton getCompute_UUCP() {
        return compute_UUCP;
    }

    public void setCompute_UUCP(JButton compute_UUCP) {
        this.compute_UUCP = compute_UUCP;
    }

    public int[] getTcfArray() {
        return tcfArray;
    }

    public void setTcfArray(int[] tcfArray) {
        this.tcfArray = tcfArray;
    }

    public double getTcfSum() {
        return tcfSum;
    }

    public void setTcfSum(double tcfSum) {
        this.tcfSum = tcfSum;
        tcf_total_textfield.setText(Double.toString(tcfSum));
    }

    public int[] getEcfArray() {
        return ecfArray;
    }

    public void setEcfArray(int[] ecfArray) {
        this.ecfArray = ecfArray;
    }

    public double getEcfSum() {
        return ecfSum;
    }

    public void setEcfSum(double ecfSum) {
        this.ecfSum = ecfSum;
        ecf_total_textfield.setText(Double.toString(ecfSum));
    }
    
    public int getPF() {
        return PF;
    }

    public void setPF(int PF) {
        this.PF = PF;
    }

    public int getLOC_pm() {
        return LOC_pm;
    }

    public void setLOC_pm(int LOC_pm) {
        this.LOC_pm = LOC_pm;
    }

    public int getLOC_UCP() {
        return LOC_UCP;
    }

    public void setLOC_UCP(int LOC_UCP) {
        this.LOC_UCP = LOC_UCP;
    }

    @Override
    public String toString() {
        return "UseCasePointsPane{" + "UUCW_simple=" + UUCW_simple + ", UUCW_average=" + UUCW_average + ", UUCW_complex=" + UUCW_complex + ", UUCW_total=" + UUCW_total + ", UAW_simple=" + UAW_simple + ", UAW_average=" + UAW_average + ", UAW_complex=" + UAW_complex + ", UAW_total=" + UAW_total + ", UUCP=" + UUCP + ", tcfArray=" + tcfArray + ", tcfSum=" + tcfSum + ", ecfArray=" + ecfArray + ", productivityFactor=" + PF + ", LOC_pm=" + LOC_pm + ", LOC_UCP=" + LOC_UCP + '}';
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compute_UUCP;
    private javax.swing.JButton ecf_Button;
    private javax.swing.JTextField ecf_total_textfield;
    private javax.swing.JButton estimatedHours_button;
    private javax.swing.JTextField estimatedHours_textfield;
    private javax.swing.JButton estimatedLOC_button;
    private javax.swing.JTextField estimatedLOC_textfield;
    private javax.swing.JButton estimatedPM_button;
    private javax.swing.JTextField estimatedPM_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField loc_pm_textfield;
    private javax.swing.JTextField loc_ucp_textfield;
    private javax.swing.JTextField productivityFactor_textfield;
    private javax.swing.JButton tcf_Button;
    private javax.swing.JTextField tcf_total_textfield;
    private javax.swing.JTextField uaw_average_textfield;
    private javax.swing.JTextField uaw_complex_textfield;
    private javax.swing.JTextField uaw_simple_textfield;
    private javax.swing.JTextField uaw_total_textfield;
    private javax.swing.JButton ucp_button;
    private javax.swing.JTextField ucp_textfield;
    private javax.swing.JTextField uucw_average_textfield;
    private javax.swing.JTextField uucw_complex_textfield;
    private javax.swing.JTextField uucw_simple_textfield;
    private javax.swing.JTextField uucw_total_textfield;
    private javax.swing.JTextField value_UUCP_textfield;
    // End of variables declaration//GEN-END:variables
}
